{{- if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "nis.fullname" . }}
  labels:
    {{- include "nis.labels" . | nindent 4 }}
  {{- with .Values.secretProviderClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.secretProviderClass.parameters }}
  parameters:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  provider: {{ .Values.secretProviderClass.provider }}
  {{- with .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
